### PR TITLE
Make sliders work

### PR DESCRIPTION
**Pull request by ddsnowboard**
Sliders mostly kinda work now. Anything that relies on messages (namely, closeness) still doesn't work, but everything else does. I think. The code is very rickety, so don't breathe on it too hard, and it's slow, but it's functional. And the merge conflicts shouldn't (fingers crossed) be too bad because I rebased a week ago. 

Also I tried to fix the merge conflicts and somehow something bad happened. It still kinda works, but worse now. I will fix it though. Eventually.

### CODE REVIEW

**Comment by ddsnowboard** [comment]
Also don't accept this yet. I am trying to reconcile the merge conflicts right now.

**Comment by dphuang2** [comment]
I tried your branch and it gave me this error: Alt

**Comment by ddsnowboard** [comment]
I have never seen that before. Although it's become clear that caching and local storage are causing unexpected issues. I'll keep working on on it. Should we close this and re open it when it's fixed or just wait?

**Comment by dphuang2** [comment]
Its your choice, you can either just keep committing to this branch ("slider") and this pull request will automatically update. Or if you want to create a new one that is fine as well. I would personally just keep committing to this branch and keep it open.

**Comment by ddsnowboard** [comment]
Ok. Also I found out how to reproduce it. It only appears on Chrome. Hopefully I can fix it tonight. We shall see...

**Comment by ddsnowboard** [comment]
I'm about 83% sure I fixed everything. Or at least everything necessary to be able to merge without breaking everything.

**Comment by ddsnowboard** [comment]
Finally finished everything. If someone wants to try and run it that would be great but I think it's good.

**Comment by dphuang2** [comment]
screen shot 2018-02-07 at 1 55 14 am

I am getting this error...

**Comment by ddsnowboard** [comment]
Well that is troubling. I'll see if I can fix it.

**Comment by ddsnowboard** [comment]
I'm almost sure I got everything this time. I tested on Chrome, I promise. That said, if someone else wants to do it to, that would probably be good.

**Comment by dphuang2** [comment]
Yay!

edit: There were a lot of problems merging....looking into this.

**Pull request merged**
